# Generated by Django 4.2.16 on 2026-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.IntegerField(blank=True, null=True, verbose_name='current semester'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='is student'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, default='Universidad Pontificia Bolivariana', max_length=255, verbose_name='university'),
        ),
    ]
