# Generated by Django 4.2.16 on 2026-10-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.IntegerField(default=100),
        ),
    ]
